# Site Configuration

# Theme, mapped to the directory: ./theme/xxxx
theme: default

# HTML Language setting
lang: "en"

# Plugins, implemented in ./plugins/PLUGIN_NAME
# Use {{ vars.PLUGIN_NAME }} in the settings below

# The output of the plugin can be used below, e.g., {{vars.MediumFollowersCountPlugin}}
plugins:
  # Automatically fetch Medium follower count
  - MediumFollowersCountPlugin:
      username: vPam
  # Automatically fetch Github repo star count
  - GithubRepoStarsCountPlugin:
      - vPamm/ChatDJ
      - vPamm/dennis

# Google Analytics tracking id
google_analytics_id:

# HTML Title
title: "vPam's Links"

# Avatar image path
avatar: "./images/profile.jpeg"

# Name section text
name: "pam"

# Tagline section text
tagline: >-
    a funny person

# List of links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# text: The displayed text for the link
# title: The url title
# url: The URL of the link
# alt: Alternative text for accessibility
# target: `_blank` opens in a new tab, `_self` opens in the same frame
links:
  - link:
      icon: "fa-brands fa-github"
      text: "chatdj <span class='link-button-text'>({{vars.GithubRepoStarsCountPlugin['vPamm/ChatDJ']}} Stars)</span>"
      url: "https://github.com/vPamm/ChatDJ"
      alt: "A Twitch bot for managing Spotify playlists and handling song requests via channel point redemptions."
      title: "A Twitch bot for managing Spotify playlists and handling song requests via channel point redemptions."
      target: "_blank"
  - link:
      icon: "fa-brands fa-youtube"
      text: "watch my latest main channel video"
      url: ""
      target: "_blank"

  - link:
      icon: "fa-brands fa-youtube"
      text: "Watch my latest racing video"
      url: ""
      target: "_blank"


# List of social media links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# title: The url title
# url: The URL of the social media link
# alt: Alternative text for accessibility
# target: _blank opens in a new tab, _self opens in the same frame
socials:
  - social:
      icon: "fa-brands fa-github"
      url: "https://github.com/vPamm"
      title: "GitHub"
      alt: "vPam's GitHub"
      target: "_blank"
  - social:
      icon: "fa-brands fa-twitter"
      url: "https://twitter.com/pamsexuals"
      title: "Twitter"
      alt: "vPam's Twitter"
      target: "_blank"
  - social:
      icon: "fa-brands fa-youtube"
      url: "https://youtube.com/vPamm"
      title: "Main Channel"
      alt: "vPam YouTube Channel"
      target: "_blank"
  - social:
      icon: "fa-brands fa-tiktok"
      url: "https://www.tiktok.com/pamsexuals"
      title: "Main TikTok"
      alt: "vPam TikTok"
      target: "_blank"
  - social:
      icon: "fa-brands fa-youtube"
      url: "https://www.youtube.com/@vPamGoesRacing"
      title: "Racing Channel"
      alt: "Pam Goes Racing YouTube Channel"
      target: "_blank"
  - social:
      icon: "fa-brands fa-tiktok"
      url: "https://www.tiktok.com/pamgoesracing"
      title: "Racing TikTok"
      alt: "Pam Goes Racing TikTok"
      target: "_blank"

# Footer text
footer: >
    subscribe to vPam

# Footer copyright message
# Linkyee is a 100% free, open-source project—feel free to modify the copyright message as you like. :)
copyright: >
  © 2024  <a href="https://zhgchg.li" target="_blank">vPam</a>. Powered by <a href="https://github.com/vPam/linkyee" target="_blank">linkyee</a>
